// Aurora Design System - Icon Components
// Re-exports Material-UI icons with Aurora naming convention

export {
  Menu as AuroraMenuIcon,
  Dashboard as AuroraDashboardIcon,
  Work as AuroraWorkIcon,
  People as AuroraPeopleIcon,
  Settings as AuroraSettingsIcon,
  Search as AuroraSearchIcon,
  Notifications as AuroraNotificationsIcon,
  Lightbulb as AuroraLightbulbIcon,
  Language as AuroraLanguageIcon,
  Save as AuroraSaveIcon,
  ArrowBack as AuroraArrowBackIcon,
  Delete as AuroraDeleteIcon,
  Add as AuroraAddIcon,
  Block as AuroraBlockIcon,
  CheckCircle as AuroraCheckCircleIcon,
  Login as AuroraLoginIcon,
  MoreHoriz as AuroraMoreHorizIcon,
  ViewList as AuroraViewListIcon,
  ViewModule as AuroraViewModuleIcon,
  UploadFile as AuroraUploadFileIcon,
  ExpandLess as AuroraExpandLessIcon,
  ExpandMore as AuroraExpandMoreIcon,
  Business as AuroraBusinessIcon,
  Domain as AuroraDomainIcon,
  Edit as AuroraEditIcon,
  ArrowUpward as AuroraArrowUpwardIcon,
  ArrowDownward as AuroraArrowDownwardIcon,
  PersonAdd as AuroraPersonAddIcon,
  CameraAlt as AuroraCameraAltIcon,
  Close as AuroraCloseIcon,
  DragIndicator as AuroraDragIndicatorIcon,
  Description as AuroraDescriptionIcon,
  Send as AuroraSendIcon,
  Download as AuroraDownloadIcon,
  Upload as AuroraUploadIcon,
  Email as AuroraEmailIcon,
  Lock as AuroraLockIcon,
  FilterList as AuroraFilterListIcon,
  CalendarMonth as AuroraCalendarMonthIcon,
  Link as AuroraLinkIcon,
} from '@mui/icons-material';